name: 编译预发布版-gnb

on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
  TAG: ver1.4.5.b
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - name: Init submodules
        uses: snickerbockers/submodules-init@v4
      - name: 编译
        run: |
          mkdir -p /opt/musl_gcc 
          sudo timedatectl set-timezone "Asia/Shanghai"
          wget -q -c https://downloads.openwrt.org/releases/22.03.5/targets/ramips/mt7621/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz -P /opt/musl_gcc/
          tar xJf /opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz -C /opt/musl_gcc/
          wget -q -c https://downloads.openwrt.org/releases/22.03.6/targets/x86/64/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz -P /opt/musl_gcc/
          wget -q -c https://downloads.openwrt.org/releases/23.05.2/targets/mediatek/filogic/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz -P /opt/musl_gcc/
          tar xJf /opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz -C /opt/musl_gcc/
          tar xJf /opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz -C /opt/musl_gcc/
          
          export CC=/opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-gcc
          export LD=/opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-ld
          export AR=/opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-ar
          export RANLIB=/opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-ranlib
          export STAGING_DIR=/opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl
          git clone https://github.com/gnbdev/opengnb -b ${{env.TAG}} /opt/gnb
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          tar -xvf /opt/st/upx-4.1.0-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-4.1.0-amd64_linux/upx
          cd /opt
          zip -r opengnb-${{env.TAG}}-src.zip gnb
          cd /opt/gnb
          sed -i 's|-L/usr/lib -pthread| -pthread -static|g' ./Makefile.openwrt
          sed -i 's|-ffunction-sections|-ffunction-sections -static|g' ./Makefile.openwrt
          sed -i 's/1005|10.1.0.5|255.255.0.0/1005|10.1.0.5|255.255.0.0,1006|10.1.0.6|255.255.0.0,1007|10.1.0.7|255.255.0.0,1008|10.1.0.8|255.255.0.0,1009|10.1.0.9|255.255.0.0,1010|10.1.0.10|255.255.0.0,1011|10.1.0.11|255.255.0.0,1012|10.1.0.12|255.255.0.0,1013|10.1.0.13|255.255.0.0,1014|10.1.0.14|255.255.0.0,1015|10.1.0.15|255.255.0.0,1016|10.1.0.16|255.255.0.0,1017|10.1.0.17|255.255.0.0,1018|10.1.0.18|255.255.0.0,1019|10.1.0.19|255.255.0.0,1020|10.1.0.20|255.255.0.0,1021|10.1.0.21|255.255.0.0,1022|10.1.0.22|255.255.0.0,1023|10.1.0.23|255.255.0.0,1024|10.1.0.24|255.255.0.0,1025|10.1.0.25|255.255.0.0,1026|10.1.0.26|255.255.0.0,1027|10.1.0.27|255.255.0.0,1028|10.1.0.28|255.255.0.0,1029|10.1.0.29|255.255.0.0,1030|10.1.0.30|255.255.0.0/g' ./src/gnb_config_lite.c
          sed -i 's/1030|10.1.0.30|255.255.0.0/1030|10.1.0.30|255.255.0.0,1031|10.1.0.31|255.255.0.0,1032|10.1.0.32|255.255.0.0,1033|10.1.0.33|255.255.0.0,1034|10.1.0.34|255.255.0.0,1035|10.1.0.35|255.255.0.0,1036|10.1.0.36|255.255.0.0,1037|10.1.0.37|255.255.0.0,1038|10.1.0.38|255.255.0.0,1039|10.1.0.39|255.255.0.0,1040|10.1.0.40|255.255.0.0,1041|10.1.0.41|255.255.0.0,1042|10.1.0.42|255.255.0.0,1043|10.1.0.43|255.255.0.0,1044|10.1.0.44|255.255.0.0,1045|10.1.0.45|255.255.0.0,1046|10.1.0.46|255.255.0.0,1047|10.1.0.47|255.255.0.0,1048|10.1.0.48|255.255.0.0,1049|10.1.0.49|255.255.0.0,1050|10.1.0.50|255.255.0.0/g' ./src/gnb_config_lite.c
          make -f Makefile.openwrt
          file gnb
          mkdir -p ./upx
          cp -rf gnb ./upx/gnb
          cp -rf gnb_crypto ./upx/gnb_crypto
          cp -rf gnb_ctl ./upx/gnb_ctl
          cp -rf gnb_es ./upx/gnb_es
          cd /opt/gnb/upx
          /opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-strip /opt/gnb/upx/gnb_crypto
          /opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-strip /opt/gnb/upx/gnb_ctl
          /opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-strip /opt/gnb/upx/gnb_es
          /opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-strip /opt/gnb/upx/gnb
          /opt/upx-3.95-amd64_linux/upx --lzma --best gnb
          /opt/upx-3.95-amd64_linux/upx --lzma --best gnb_crypto
          /opt/upx-3.95-amd64_linux/upx --lzma --best gnb_ctl
          /opt/upx-3.95-amd64_linux/upx --lzma --best gnb_es
          cd /opt/gnb
          cp -rf /opt/gnb/examples/node_config_example node_config_example
          zip -r gnb-musl-openwrt_mipsel.zip gnb_crypto gnb_ctl gnb_es gnb upx node_config_example
          make -f Makefile.openwrt clean
          rm -rf upx
          make -f Makefile.linux
          file gnb
          mkdir -p ./upx
          cp -rf gnb ./upx/gnb
          cp -rf gnb_crypto ./upx/gnb_crypto
          cp -rf gnb_ctl ./upx/gnb_ctl
          cp -rf gnb_es ./upx/gnb_es
          cd /opt/gnb/upx
          /opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-strip /opt/gnb/upx/gnb_crypto
          /opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-strip /opt/gnb/upx/gnb_ctl
          /opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-strip /opt/gnb/upx/gnb_es
          /opt/musl_gcc/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin/mipsel-openwrt-linux-musl-strip /opt/gnb/upx/gnb
          /opt/upx-3.95-amd64_linux/upx --lzma --best gnb
          /opt/upx-3.95-amd64_linux/upx --lzma --best gnb_crypto
          /opt/upx-3.95-amd64_linux/upx --lzma --best gnb_ctl
          /opt/upx-3.95-amd64_linux/upx --lzma --best gnb_es
          cd /opt/gnb
          cp -rf /opt/gnb/examples/node_config_example node_config_example
          zip -r gnb-musl-linux-openwrt_mipsel.zip gnb_crypto gnb_ctl gnb_es gnb upx node_config_example
          make -f Makefile.linux clean
          rm -rf upx
          
          export CC=/opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-gcc
          export LD=/opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-ld
          export AR=/opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-ar
          export RANLIB=/opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-ranlib
          export STAGING_DIR=/opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl
          make -f Makefile.openwrt
          file gnb
          mkdir -p ./upx
          cp -rf gnb ./upx/gnb
          cp -rf gnb_crypto ./upx/gnb_crypto
          cp -rf gnb_ctl ./upx/gnb_ctl
          cp -rf gnb_es ./upx/gnb_es
          cd /opt/gnb/upx
          /opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_crypto
          /opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_ctl
          /opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_es
          /opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-strip /opt/gnb/upx/gnb
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_crypto
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_ctl
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_es
          cd /opt/gnb
          cp -rf /opt/gnb/examples/node_config_example node_config_example
          zip -r gnb-musl-openwrt-x86_64.zip gnb_crypto gnb_ctl gnb_es gnb upx node_config_example
          make -f Makefile.openwrt clean
          rm -rf upx
          
          make -f Makefile.linux
          file gnb
          mkdir -p ./upx
          cp -rf gnb ./upx/gnb
          cp -rf gnb_crypto ./upx/gnb_crypto
          cp -rf gnb_ctl ./upx/gnb_ctl
          cp -rf gnb_es ./upx/gnb_es
          cd /opt/gnb/upx
          /opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_crypto
          /opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_ctl
          /opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_es
          /opt/musl_gcc/openwrt-toolchain-22.03.6-x86-64_gcc-11.2.0_musl.Linux-x86_64/toolchain-x86_64_gcc-11.2.0_musl/bin/x86_64-openwrt-linux-musl-strip /opt/gnb/upx/gnb
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_crypto
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_ctl
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_es
          cd /opt/gnb
          cp -rf /opt/gnb/examples/node_config_example node_config_example
          zip -r gnb-musl-linux-x86_64.zip gnb_crypto gnb_ctl gnb_es gnb upx node_config_example
          make -f Makefile.linux clean
          rm -rf upx
          
          export CC=/opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-gcc
          export LD=/opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-ld
          export AR=/opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-ar
          export RANLIB=/opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-ranlib
          export STAGING_DIR=/opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl
          make -f Makefile.openwrt
          file gnb
          mkdir -p ./upx
          cp -rf gnb ./upx/gnb
          cp -rf gnb_crypto ./upx/gnb_crypto
          cp -rf gnb_ctl ./upx/gnb_ctl
          cp -rf gnb_es ./upx/gnb_es
          cd /opt/gnb/upx
          /opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_crypto
          /opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_ctl
          /opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_es
          /opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-strip /opt/gnb/upx/gnb
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_crypto
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_ctl
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_es
          cd /opt/gnb
          cp -rf /opt/gnb/examples/node_config_example node_config_example
          zip -r gnb-musl-openwrt_aarch64_cortex-a53.zip gnb_crypto gnb_ctl gnb_es gnb upx node_config_example
          make -f Makefile.openwrt clean
          rm -rf upx
          
          make -f Makefile.linux
          file gnb
          mkdir -p ./upx
          cp -rf gnb ./upx/gnb
          cp -rf gnb_crypto ./upx/gnb_crypto
          cp -rf gnb_ctl ./upx/gnb_ctl
          cp -rf gnb_es ./upx/gnb_es
          cd /opt/gnb/upx
          /opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_crypto
          /opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_ctl
          /opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-strip /opt/gnb/upx/gnb_es
          /opt/musl_gcc/openwrt-toolchain-23.05.2-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-musl-strip /opt/gnb/upx/gnb
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_crypto
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_ctl
          /opt/upx-4.1.0-amd64_linux/upx --lzma --best gnb_es
          cd /opt/gnb
          cp -rf /opt/gnb/examples/node_config_example node_config_example
          zip -r gnb-musl-linux_aarch64_cortex-a53.zip gnb_crypto gnb_ctl gnb_es gnb upx node_config_example
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}
           
           gnb-musl-**.zip     二进制文件，其中upx为压缩版二进制文件减少体积占用
           opengnb-${{env.TAG}}-src.zip 版本源码文件

           lite模式增加到50个节点[（1001|10.1.0.1|255.255.0.0 至 1050|10.1.0.50|255.255.0.0）](https://github.com/gnbdev/opengnb/blob/25ff34122f9f5ef73d84e38efed4ebb8944051f4/src/gnb_config_lite.c#L325C48-L325C73)
           
           [官方更新说明](https://github.com/gnbdev/opengnb/releases)
           
          tag_name: ${{env.TAG}}
          prerelease: true
          files: |
           /opt/gnb/gnb-musl-openwrt_mipsel.zip
           /opt/gnb/gnb-musl-openwrt-x86_64.zip
           /opt/gnb/gnb-musl-openwrt_aarch64_cortex-a53.zip
           /opt/gnb/gnb-musl-linux_mipsel.zip
           /opt/gnb/gnb-musl-linux-x86_64.zip
           /opt/gnb/gnb-musl-linux_aarch64_cortex-a53.zip
           /opt/opengnb-${{env.TAG}}-src.zip
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
